import ReactMarkdown from 'react-markdown';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { oneDark } from 'react-syntax-highlighter/dist/esm/styles/prism';
import { useState, useRef } from 'react';

export default function MessageBubble({ role, content, time, type }) {
  const [copied, setCopied] = useState(false);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const contentRef = useRef(null);

  const isImage = type === 'image' || (role === 'assistant' && typeof content === 'string' && content.match(/^https?:\/\/.*(grok|x\.ai|twitter|openai).*\.(png|jpg|webp)/i)) || (role === 'assistant' && typeof content === 'string' && content.startsWith('http') && content.length < 500 && !content.includes(' '));

  const isCV = !isImage && role === 'assistant' && (
    (content.includes("# CV") || content.includes("## CV") || content.includes("Curriculum Vitae")) &&
    (content.includes("Expérience") || content.includes("Formation") || content.includes("Compétences"))
  );

  const isCoverLetter = !isImage && role === 'assistant' && (
    (content.includes("Objet :") || content.includes("Objet:")) &&
    (content.includes("Madame") || content.includes("Monsieur") || content.includes("Lettre de motivation"))
  );

  const handleCopy = (code) => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const generatePDF = async () => {
    if (!contentRef.current) return;
    setIsGeneratingPdf(true);

    try {
      const html2pdf = (await import('html2pdf.js')).default;
      
      const element = document.createElement('div');
      element.innerHTML = contentRef.current.innerHTML;
      
      element.style.width = '100%';
      element.style.padding = '20px';
      element.style.background = 'white';
      element.style.color = 'black';
      element.style.fontFamily = 'Arial, Helvetica, sans-serif';
      element.style.fontSize = '12px';
      element.style.lineHeight = '1.5';
      
      const buttons = element.querySelectorAll('button');
      buttons.forEach(btn => btn.remove());
      
      const h1s = element.querySelectorAll('h1');
      h1s.forEach(h => { h.style.fontSize = '24px'; h.style.borderBottom = '2px solid #333'; h.style.paddingBottom = '10px'; h.style.marginBottom = '20px'; });
      
      const h2s = element.querySelectorAll('h2');
      h2s.forEach(h => { h.style.fontSize = '18px'; h.style.borderBottom = '1px solid #ccc'; h.style.paddingBottom = '5px'; h.style.marginTop = '20px'; h.style.marginBottom = '10px'; h.style.color = '#2c3e50'; });

      const opt = {
        margin:       10,
        filename:     isCV ? 'mon_cv.pdf' : 'ma_lettre.pdf',
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2 },
        jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
      };

      await html2pdf().set(opt).from(element).save();

    } catch (e) {
      console.error("Erreur génération PDF:", e);
      alert("Une erreur est survenue lors de la génération du PDF.");
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  return (
    <div className={`message ${role}`}>
      <div className="message-bubble">
        <div className="message-sender">
          {role === 'user' ? 'Vous' : 'Grok'}
        </div>
        
        <div className="markdown-content" ref={contentRef}>
          {isImage ? (
            <div className="image-container">
              <img src={content} alt="Generated by AI" className="generated-image" style={{ maxWidth: '100%', borderRadius: '8px' }} />
            </div>
          ) : role === 'user' ? (
            <p>{content}</p>
          ) : (
            <ReactMarkdown
              components={{
                code({node, inline, className, children, ...props}) {
                  const match = /language-(\w+)/.exec(className || '');
                  const codeString = String(children).replace(/\n$/, '');
                  
                  return !inline && match ? (
                    <div className="code-block-wrapper">
                      <div className="code-header">
                        <span>{match[1]}</span>
                        <button 
                          className="copy-btn" 
                          onClick={() => handleCopy(codeString)}
                        >
                          {copied ? 'Copié !' : 'Copier'}
                        </button>
                      </div>
                      <SyntaxHighlighter
                        style={oneDark}
                        language={match[1]}
                        PreTag="div"
                        {...props}
                      >
                        {codeString}
                      </SyntaxHighlighter>
                    </div>
                  ) : (
                    <code className={className} {...props}>
                      {children}
                    </code>
                  );
                }
              }}
            >
              {content}
            </ReactMarkdown>
          )}
        </div>

        {(isCV || isCoverLetter) && (
          <div className="pdf-action-container">
            <button 
              onClick={generatePDF} 
              className="download-pdf-btn"
              disabled={isGeneratingPdf}
            >
              {isGeneratingPdf ? 'Génération...' : (
                <>
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                    <polyline points="14 2 14 8 20 8"></polyline>
                    <line x1="16" y1="13" x2="8" y2="13"></line>
                    <line x1="16" y1="17" x2="8" y2="17"></line>
                    <polyline points="10 9 9 9 8 9"></polyline>
                  </svg>
                  Télécharger en PDF
                </>
              )}
            </button>
          </div>
        )}

        <div className="message-time">
           {time ? new Date(time).toLocaleTimeString() : ''}
        </div>
      </div>
    </div>
  );
}
