import ReactMarkdown from 'react-markdown';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { oneDark } from 'react-syntax-highlighter/dist/esm/styles/prism';
import { useState } from 'react';

export default function MessageBubble({ role, content, time, type }) {
  const [copied, setCopied] = useState(false);

  const isImage = type === 'image' || (role === 'assistant' && typeof content === 'string' && content.match(/^https?:\/\/.*(grok|x\.ai|twitter|openai).*\.(png|jpg|webp)/i)) || (role === 'assistant' && typeof content === 'string' && content.startsWith('http') && content.length < 500 && !content.includes(' '));

  const handleCopy = (code) => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className={`message ${role}`}>
      <div className="message-bubble">
        <div className="message-sender">
          {role === 'user' ? 'Vous' : 'Grok'}
        </div>
        
        <div className="markdown-content">
          {isImage ? (
            <div className="image-container">
              <img src={content} alt="Generated by AI" className="generated-image" style={{ maxWidth: '100%', borderRadius: '8px' }} />
            </div>
          ) : role === 'user' ? (
            <p>{content}</p>
          ) : (
            <ReactMarkdown
              components={{
                code({node, inline, className, children, ...props}) {
                  const match = /language-(\w+)/.exec(className || '');
                  const codeString = String(children).replace(/\n$/, '');
                  
                  return !inline && match ? (
                    <div className="code-block-wrapper">
                      <div className="code-header">
                        <span>{match[1]}</span>
                        <button 
                          className="copy-btn" 
                          onClick={() => handleCopy(codeString)}
                        >
                          {copied ? 'Copié !' : 'Copier'}
                        </button>
                      </div>
                      <SyntaxHighlighter
                        style={oneDark}
                        language={match[1]}
                        PreTag="div"
                        {...props}
                      >
                        {codeString}
                      </SyntaxHighlighter>
                    </div>
                  ) : (
                    <code className={className} {...props}>
                      {children}
                    </code>
                  );
                }
              }}
            >
              {content}
            </ReactMarkdown>
          )}
        </div>

        <div className="message-time">
           {time ? new Date(time).toLocaleTimeString() : ''}
        </div>
      </div>
    </div>
  );
}
